# Generated by Django 4.0.2 on 2022-02-15 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_category_subcategory_category_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='category',
        ),
        migrations.AddField(
            model_name='medicament',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.subcategory'),
        ),
    ]
