# Generated by Django 4.0.2 on 2022-02-16 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_medicament_category_medicament_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategorye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='medicament',
            name='subcategorye',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.subcategorye'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subcategorye',
            field=models.ManyToManyField(blank=True, null=True, to='store.Subcategorye'),
        ),
    ]
