# Generated by Django 4.0.2 on 2022-02-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_category_name_alter_medicament_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='medicament-images/%y/%m'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='image',
            field=models.ImageField(upload_to='medicament-images/%y/%m'),
        ),
    ]
