# Generated by Django 4.0.2 on 2022-02-18 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_medicament_image2_alter_medicament_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='image2',
        ),
    ]
