# Generated by Django 4.0.2 on 2022-02-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_medicament_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='quantite',
            field=models.IntegerField(default=100),
        ),
    ]
