# Generated by Django 3.2.8 on 2022-02-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_medicament_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subcategory',
            field=models.ManyToManyField(blank=True, to='store.Subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategorye',
            field=models.ManyToManyField(blank=True, to='store.Subcategorye'),
        ),
    ]
