# Generated by Django 3.2.8 on 2022-02-22 12:40

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20220222_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='tel',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[store.validators.validate_length]),
        ),
    ]
