# Generated by Django 3.2.8 on 2022-02-22 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
