# Generated by Django 3.2.8 on 2022-02-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20220222_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeitem',
            name='favorable_by',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
