# Generated by Django 3.2.8 on 2022-02-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_commandeitem_favorable_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandeitem',
            name='commande',
        ),
        migrations.AddField(
            model_name='commande',
            name='items',
            field=models.ManyToManyField(to='store.CommandeItem'),
        ),
    ]
