# Generated by Django 3.2.8 on 2022-02-23 10:07

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_alter_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='username',
        ),
        migrations.AddField(
            model_name='commande',
            name='adresse',
            field=models.CharField(default='Arianna', max_length=200),
        ),
        migrations.AddField(
            model_name='commande',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='phone',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[store.validators.validate_length]),
        ),
        migrations.AddField(
            model_name='commande',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
