# Generated by Django 3.2.8 on 2022-02-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_auto_20220223_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
