# Generated by Django 3.2.8 on 2022-03-04 09:34

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default='23601888', max_length=8, validators=[store.validators.validate_length]),
        ),
    ]
