# Generated by Django 4.0.2 on 2022-03-12 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_remove_subcategory_image_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='gender',
        ),
    ]
